# Generated by Django 4.2.30 on 2026-05-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Na čekanju'), ('accepted', 'Prihvaćena'), ('declined', 'Odbijena'), ('completed', 'Završena'), ('cancelled', 'Otkazana')], default='pending', max_length=12),
        ),
    ]
