# Generated by Django 5.2.14 on 2026-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_listing_expires_at_alter_listing_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="expiry_reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("message", "Nova poruka"),
                    ("offer", "Nova ponuda"),
                    ("offer_accepted", "Ponuda prihvaćena"),
                    ("offer_declined", "Ponuda odbijena"),
                    ("review", "Nova recenzija"),
                    ("listing_expiring", "Oglas uskoro ističe"),
                ],
                default="message",
                max_length=20,
            ),
        ),
    ]
